---
name: Bump the `netlify-deploy` CLI version

scms:
  default:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: "{{ .github.owner }}"
      repository: "{{ .github.repository }}"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      branch: "{{ .github.branch }}"

sources:
  lastVersion:
    kind: githubrelease
    name: get the latest netlify-deploy CLI version
    spec:
      owner: "halkeye"
      repository: "netlify-golang-deploy"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      versionfilter:
        kind: semver
    transformers:
      - trimprefix: v

conditions:
  testDockerfile:
    name: "Does the Dockerfile have an ARG instruction which key is NETLIFY_DEPLOY?"
    kind: dockerfile
    disablesourceinput: true
    spec:
      file: Dockerfile
      instruction:
        keyword: "ARG"
        matcher: "NETLIFY_DEPLOY"
  testTestHarness:
    name: "Does the test harness checks for a label io.jenkins-infra.tools.netlify-deploy.version?"
    kind: yaml
    disablesourceinput: true
    spec:
      file: "cst.yml"
      key: "$.metadataTest.labels[4].key"
      value: io.jenkins-infra.tools.netlify-deploy.version

targets:
  updateTestVersion:
    name: "Update the test harness"
    sourceid: lastVersion
    kind: yaml
    spec:
      file: "cst.yml"
      key: "$.metadataTest.labels[4].value"
    scmid: default
  updateDockerfileVersion:
    name: "Update the value of ARG NETLIFY_DEPLOY in the Dockerfile"
    sourceid: lastVersion
    kind: dockerfile
    spec:
      file: Dockerfile
      instruction:
        keyword: "ARG"
        matcher: "NETLIFY_DEPLOY"
    scmid: default

actions:
  default:
    kind: github/pullrequest
    scmid: default
    title: Bump the `netlify-deploy` CLI version to {{ source "lastVersion" }}
    spec:
      labels:
        - dependencies
        - netlify-deploy
