---
name: Release Drafter

on:
  workflow_dispatch:
  push:
  release:

# Only allow 1 release-drafter build at a time to avoid creating multiple "next" releases
concurrency: "release-drafter"

jobs:
  update_release_draft:
    runs-on: ubuntu-20.04
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          # This token is generated automatically by default in GitHub Actions: no need to create it manually
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
...
